name: new PURL
description: Request a new PURL
title: "[NEW] <title>"
body:
- type: input
  id: pname
  attributes:
    label: Contact person name
    description: The name of the contact person.
  validations:
    required: false
- type: input
  id: pemail
  attributes:
    label: Contact person email.
    description: The email of the contact person.
  validations:
    required: false
- type: textarea
  id: overview
  attributes:
    label: Overview in the README.md
    description: Could you please give a brief description of what this PID is being redirected to?
    validations:
    required: false
- type: input
  id: prefix
  attributes:
    label: What is your resource prefix(es)?
    description: |
      E.g., foaf as of FOAF ontology.
    placeholder: foaf
    validations:
    required: true
- type: input
  id: url
  attributes:
    label: Where is the resource located on the Web (i.e. the URL)?
    description: |
      The actual URL of the resource, i.e. a functional URL.
    placeholder: foaf
    validations:
    required: true
- type: checkboxes
  id: contentnego
  attributes:
    label: Do you want to enable content negotiation?
    description: If yes, proceed to the next section otherwise, skip and submit your issue.
    options:
    - label: enable content negotiation
      required: false
- type: dropdown
  id: Resourcetype
  attributes:
    label: Resource type
    description: Please select all available representations of your resource
    multiple: true
    options:
      - HTML
      - RDF/XML
      - TTL
      - OWL
      - N-triples
      - N3
