name: new PURL
description: Request a new PURL
title: "[NEW] <title>"
body:
- type: input
  id: pname
  attributes:
    label: Contact person name
    description: The name of the contact person.
  validations:
    required: false
